//! The Chat: conversations saved with their questions, answers and sources. Answers are
//! generated by the RAG engine; text streams through `on_token` while it is generated.

use std::sync::Arc;

use nlmx_domain::{
    chat::{
        Conversation, ConversationId, ConversationSummary, Message, MessageId, MessagePageRef,
        MessageSource, MessageStatus, Role,
    },
    generation::{LanguageModelStatus, UnavailableKind},
    ingestion::DocumentId,
};

use crate::{
    ports::{CancelFlag, ConversationRepository, FinishedAnswer, StorageError},
    services::rag::{
        AnswerStatus, HistoryTurn, RagAnswer, RagEngine, RagError, RagOptions, context::Source,
    },
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ChatError {
    NotFound,
    /// The message is not an answer waiting to be generated.
    NotPending,
    EmptyQuestion,
    Storage(String),
}

impl std::fmt::Display for ChatError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound => f.write_str("conversa ou mensagem não encontrada"),
            Self::NotPending => f.write_str("esta resposta não está aguardando geração"),
            Self::EmptyQuestion => f.write_str("escreva uma pergunta"),
            Self::Storage(m) => f.write_str(m),
        }
    }
}

impl From<StorageError> for ChatError {
    fn from(e: StorageError) -> Self {
        Self::Storage(e.message)
    }
}

/// Earlier exchanges used to understand follow-up questions.
const HISTORY_TURNS: usize = 3;
const TITLE_CHARS: usize = 60;

pub struct ChatService {
    pub conversations: Arc<dyn ConversationRepository>,
    pub rag: Arc<RagEngine>,
    pub options: RagOptions,
}

impl ChatService {
    /// The most recent conversation, or a new one.
    pub async fn current(&self) -> Result<Conversation, ChatError> {
        match self.conversations.recent(1).await?.first() {
            Some(summary) => self
                .conversations
                .get(summary.id)
                .await?
                .ok_or(ChatError::NotFound),
            None => Ok(self.conversations.create(None).await?),
        }
    }

    pub async fn conversation(&self, id: ConversationId) -> Result<Conversation, ChatError> {
        self.conversations.get(id).await?.ok_or(ChatError::NotFound)
    }

    /// A new conversation keeping the given scope.
    pub async fn start(&self, document: Option<DocumentId>) -> Result<Conversation, ChatError> {
        Ok(self.conversations.create(document).await?)
    }

    pub async fn recent(&self, limit: u32) -> Result<Vec<ConversationSummary>, ChatError> {
        Ok(self.conversations.recent(limit).await?)
    }

    pub async fn messages(&self, id: ConversationId) -> Result<Vec<Message>, ChatError> {
        Ok(self.conversations.messages(id).await?)
    }

    pub async fn message(&self, id: MessageId) -> Result<Message, ChatError> {
        self.conversations
            .message(id)
            .await?
            .ok_or(ChatError::NotFound)
    }

    pub async fn set_scope(
        &self,
        id: ConversationId,
        document: Option<DocumentId>,
    ) -> Result<(), ChatError> {
        Ok(self.conversations.set_scope(id, document).await?)
    }

    pub async fn delete(&self, id: ConversationId) -> Result<(), ChatError> {
        Ok(self.conversations.delete(id).await?)
    }

    /// Saves the question and an answer placeholder (`Streaming`); `answer` fills it.
    pub async fn ask(
        &self,
        conversation: ConversationId,
        question: &str,
    ) -> Result<(MessageId, MessageId), ChatError> {
        let question = question.trim();
        if question.is_empty() {
            return Err(ChatError::EmptyQuestion);
        }
        let current = self.conversation(conversation).await?;
        let user = self
            .conversations
            .add_message(conversation, Role::User, question, MessageStatus::Answered)
            .await?;
        let assistant = self
            .conversations
            .add_message(conversation, Role::Assistant, "", MessageStatus::Streaming)
            .await?;
        if current.title.is_none() {
            let mut title: String = question.chars().take(TITLE_CHARS).collect();
            if question.chars().count() > TITLE_CHARS {
                title.push('…');
            }
            self.conversations.set_title(conversation, &title).await?;
        }
        Ok((user, assistant))
    }

    /// Generates the answer of a `Streaming` message and saves it with its sources.
    pub async fn answer(
        &self,
        message: MessageId,
        on_token: &(dyn Fn(&str) + Send + Sync),
        cancel: CancelFlag,
    ) -> Result<Message, ChatError> {
        let pending = self.message(message).await?;
        if pending.role != Role::Assistant || pending.status != MessageStatus::Streaming {
            return Err(ChatError::NotPending);
        }
        let conversation = self.conversation(pending.conversation_id).await?;
        let messages = self.conversations.messages(conversation.id).await?;
        let position = messages
            .iter()
            .position(|m| m.id == message)
            .ok_or(ChatError::NotFound)?;
        let earlier = &messages[..position];
        let question = earlier
            .iter()
            .rev()
            .find(|m| m.role == Role::User)
            .map(|m| m.content.clone())
            .ok_or(ChatError::NotFound)?;
        let history = history(&earlier[..earlier.len().saturating_sub(1)]);

        let mut options = self.options.clone();
        if let Some(document) = conversation.document_id {
            options.retriever.filter.documents = Some(vec![document]);
        }
        let result = self
            .rag
            .converse(&question, &history, &options, on_token, cancel)
            .await;
        let (content, status, error, sources, page_refs) = outcome(result);
        self.conversations
            .finish_message(
                message,
                FinishedAnswer {
                    content: &content,
                    status,
                    error: error.as_deref(),
                    sources: &sources,
                    page_refs: &page_refs,
                },
            )
            .await?;
        self.message(message).await
    }

    /// Clears an answer so that `answer` generates it again.
    pub async fn regenerate(&self, message: MessageId) -> Result<(), ChatError> {
        let m = self.message(message).await?;
        if m.role != Role::Assistant || m.status == MessageStatus::Streaming {
            return Err(ChatError::NotPending);
        }
        Ok(self.conversations.reset_message(message).await?)
    }
}

/// Question/answer pairs that ended with an answer, most recent last.
fn history(messages: &[Message]) -> Vec<HistoryTurn> {
    let mut turns = Vec::new();
    let mut question: Option<&str> = None;
    for m in messages {
        match m.role {
            Role::User => question = Some(&m.content),
            Role::Assistant => {
                if let (Some(q), MessageStatus::Answered) = (question.take(), m.status) {
                    turns.push(HistoryTurn {
                        question: q.to_string(),
                        answer: m.content.clone(),
                    });
                }
            }
        }
    }
    let skip = turns.len().saturating_sub(HISTORY_TURNS);
    turns.into_iter().skip(skip).collect()
}

fn sources(sources: &[Source], cited: &[usize]) -> Vec<MessageSource> {
    sources
        .iter()
        .map(|s| MessageSource {
            n: s.n as u32,
            cited: cited.contains(&s.n),
            document_id: s.document_id,
            chunk_id: Some(s.chunk_id),
            document_title: s.title.clone(),
            page_start: s.page_start,
            page_end: s.page_end,
            section: s.section.clone(),
            label: s.label.clone(),
            quote: s.content.clone(),
            bboxes: s.bboxes.clone(),
        })
        .collect()
}

type Outcome = (
    String,
    MessageStatus,
    Option<String>,
    Vec<MessageSource>,
    Vec<MessagePageRef>,
);

fn outcome(result: Result<RagAnswer, RagError>) -> Outcome {
    match result {
        Ok(answer) => {
            let cited: Vec<usize> = answer.citations.iter().map(|c| c.n).collect();
            let status = match answer.status {
                AnswerStatus::Answered => MessageStatus::Answered,
                AnswerStatus::NotFound => MessageStatus::NotFound,
                AnswerStatus::Refused => MessageStatus::Refused,
                AnswerStatus::Cancelled => MessageStatus::Cancelled,
            };
            let error = (status == MessageStatus::Refused)
                .then(|| answer.warnings.last().cloned())
                .flatten();
            let page_refs = answer
                .page_refs
                .iter()
                .map(|r| MessagePageRef {
                    page: r.page,
                    document_id: r.document_id,
                    source: r.source.map(|n| n as u32),
                })
                .collect();
            (
                answer.answer,
                status,
                error,
                sources(&answer.sources, &cited),
                page_refs,
            )
        }
        Err(RagError::ModelUnavailable { status, sources: s }) => (
            String::new(),
            MessageStatus::Failed,
            Some(describe(&status)),
            sources(&s, &[]),
            Vec::new(),
        ),
        Err(e) => (
            String::new(),
            MessageStatus::Failed,
            Some(e.to_string()),
            Vec::new(),
            Vec::new(),
        ),
    }
}

/// What the user can do about an unavailable model.
pub fn describe(status: &LanguageModelStatus) -> String {
    match status {
        LanguageModelStatus::Available => "O modelo de linguagem não respondeu.".into(),
        LanguageModelStatus::LicenseRequired => "Os termos do Apple Foundation Models ainda não foram aceitos neste Mac. No Terminal, execute: sudo fm license".into(),
        LanguageModelStatus::Incompatible { reason } => reason.clone(),
        LanguageModelStatus::Unavailable { kind, reason } => match kind {
            UnavailableKind::AppleIntelligenceDisabled => "O Apple Intelligence está desativado. Ative-o em Ajustes do Sistema › Apple Intelligence e Siri.".into(),
            UnavailableKind::DeviceNotEligible => "Este Mac não é compatível com o Apple Intelligence.".into(),
            UnavailableKind::ModelNotReady => "O macOS ainda está preparando o modelo. Tente novamente em alguns minutos.".into(),
            UnavailableKind::Other => reason.clone(),
        },
    }
}
