//! `PdfiumDocumentEngine` against the real PDFium library and the fixtures in `tests/fixtures/`
//! (generated by `examples/generate_fixtures.rs`; page size 612 × 792 pt).

use std::{
    path::PathBuf,
    sync::{Arc, OnceLock},
};

use nlmx_application::ports::DocumentEngine;
use nlmx_domain::document::{DocumentError, RenderOptions};
use nlmx_pdf_pdfium::PdfiumDocumentEngine;

fn engine() -> &'static PdfiumDocumentEngine {
    static ENGINE: OnceLock<PdfiumDocumentEngine> = OnceLock::new();
    ENGINE.get_or_init(|| {
        PdfiumDocumentEngine::from_default_location().expect(
            "PDFium not available — run `make bootstrap` to download runtime/lib/libpdfium.dylib",
        )
    })
}

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn close_to(actual: f32, expected: f32, tolerance: f32) -> bool {
    (actual - expected).abs() <= tolerance
}

fn png_size(png: &[u8]) -> (u32, u32) {
    assert_eq!(&png[..8], b"\x89PNG\r\n\x1a\n", "not a PNG");
    let be = |at: usize| u32::from_be_bytes(png[at..at + 4].try_into().unwrap());
    (be(16), be(20))
}

#[tokio::test]
async fn opens_counts_pages_and_closes() {
    let doc = engine().open(&fixture("text.pdf")).await.unwrap();
    assert_eq!(engine().page_count(doc).await.unwrap(), 2);
    engine().close(doc).await.unwrap();
    assert_eq!(
        engine().page_count(doc).await,
        Err(DocumentError::UnknownHandle)
    );
    assert_eq!(engine().close(doc).await, Err(DocumentError::UnknownHandle));
}

#[tokio::test]
async fn reads_metadata() {
    let doc = engine().open(&fixture("text.pdf")).await.unwrap();
    let meta = engine().metadata(doc).await.unwrap();
    assert_eq!(meta.title.as_deref(), Some("Contrato de Exemplo"));
    assert_eq!(meta.author.as_deref(), Some("Equipe NLMX"));
    assert_eq!(meta.subject.as_deref(), Some("Fixture de teste"));
    assert_eq!(meta.keywords.as_deref(), Some("rag, teste"));
    assert_eq!(meta.producer.as_deref(), Some("NLMX"));
    assert_eq!(meta.created_at.as_deref(), Some("2026-01-02T03:04:05Z"));
    // Known upstream limitation: pdfium-render 0.9.4 looks up "ModificationDate" instead of the
    // standard "ModDate" Info key, so the fixture's ModDate is not visible (see worker.rs).
    assert_eq!(meta.modified_at, None);
    assert_eq!(meta.page_count, 2);
    assert_eq!(meta.pdf_version.as_deref(), Some("1.7"));

    let scanned = engine().open(&fixture("scanned.pdf")).await.unwrap();
    let meta = engine().metadata(scanned).await.unwrap();
    assert_eq!(
        meta.title, None,
        "missing Info dictionary means no metadata"
    );
    engine().close(doc).await.unwrap();
    engine().close(scanned).await.unwrap();
}

#[tokio::test]
async fn extracts_text_with_accents() {
    let doc = engine().open(&fixture("text.pdf")).await.unwrap();
    let page1 = engine().extract_text(doc, 1).await.unwrap();
    assert!(page1.contains("Contrato de Exemplo"), "{page1}");
    assert!(
        page1.contains("Cláusula 1 — Carência de 180 dias."),
        "{page1}"
    );
    assert!(
        page1.contains("Cobertura ambulatorial e hospitalar."),
        "{page1}"
    );
    assert_eq!(
        engine().extract_text(doc, 2).await.unwrap().trim(),
        "Página dois"
    );
    engine().close(doc).await.unwrap();
}

#[tokio::test]
async fn text_spans_carry_coordinates_and_font_information() {
    let doc = engine().open(&fixture("text.pdf")).await.unwrap();
    let spans = engine().text_spans(doc, 1).await.unwrap();
    let texts: Vec<_> = spans.iter().map(|s| s.text.as_str()).collect();
    assert_eq!(
        texts,
        [
            "Contrato de Exemplo",
            "Cláusula 1 — Carência de 180 dias.",
            "Cobertura ambulatorial e hospitalar."
        ]
    );

    let (title, paragraph, next) = (&spans[0], &spans[1], &spans[2]);
    assert!(
        title.bold && !paragraph.bold,
        "Helvetica-Bold title, regular body"
    );
    assert!(close_to(title.font_size, 18.0, 0.5) && close_to(paragraph.font_size, 11.0, 0.5));
    assert!(title.font_name.contains("Helvetica"), "{}", title.font_name);

    // Drawn at x = 72 with baselines y = 720 / 690 / 674 (bottom-left), i.e. 72 / 102 / 118 from the top.
    for (span, baseline) in [(title, 72.0), (paragraph, 102.0), (next, 118.0)] {
        assert!(close_to(span.bbox.left, 72.0, 1.5), "{span:?}");
        assert!(
            span.bbox.top < baseline && span.bbox.bottom > baseline - 2.0,
            "{span:?}"
        );
        assert!(
            span.bbox.right > span.bbox.left && span.bbox.right < 612.0,
            "{span:?}"
        );
    }
    assert!(
        title.bbox.bottom <= paragraph.bbox.top + 1.0,
        "title is above the paragraph"
    );
    assert!(
        paragraph.bbox.top < next.bbox.top,
        "reading order top to bottom"
    );
    engine().close(doc).await.unwrap();
}

#[tokio::test]
async fn detects_pages_without_text() {
    let doc = engine().open(&fixture("mixed.pdf")).await.unwrap();
    assert_eq!(engine().pages_without_text(doc).await.unwrap(), vec![2, 3]);

    let text_page = engine().page_info(doc, 1).await.unwrap();
    assert!(text_page.has_text && text_page.char_count == "Introdução".len() as u32 - 2);
    assert_eq!((text_page.width, text_page.height), (612.0, 792.0));

    let image_page = engine().page_info(doc, 2).await.unwrap();
    assert!(
        !image_page.has_text && image_page.image_count == 1,
        "OCR candidate: {image_page:?}"
    );
    let blank = engine().page_info(doc, 3).await.unwrap();
    assert!(!blank.has_text && blank.image_count == 0, "{blank:?}");

    let scanned = engine().open(&fixture("scanned.pdf")).await.unwrap();
    assert_eq!(engine().pages_without_text(scanned).await.unwrap(), vec![1]);
    engine().close(doc).await.unwrap();
    engine().close(scanned).await.unwrap();
}

#[tokio::test]
async fn extracts_images_with_position_and_pixels() {
    let doc = engine().open(&fixture("scanned.pdf")).await.unwrap();
    let images = engine().page_images(doc, 1).await.unwrap();
    assert_eq!(images.len(), 1);
    let image = &images[0];
    assert_eq!((image.width_px, image.height_px), (4, 2));
    assert_eq!(png_size(&image.png), (4, 2));
    // Drawn at x = 100, y = 500 (bottom-left), 200 × 100 pt → top-left (100, 192)–(300, 292).
    let b = image.bbox;
    assert!(
        close_to(b.left, 100.0, 0.5) && close_to(b.right, 300.0, 0.5),
        "{b:?}"
    );
    assert!(
        close_to(b.top, 192.0, 0.5) && close_to(b.bottom, 292.0, 0.5),
        "{b:?}"
    );

    let text = engine().open(&fixture("text.pdf")).await.unwrap();
    assert!(engine().page_images(text, 1).await.unwrap().is_empty());
    engine().close(doc).await.unwrap();
    engine().close(text).await.unwrap();
}

#[tokio::test]
async fn renders_pages_to_png() {
    let doc = engine().open(&fixture("text.pdf")).await.unwrap();
    let full = engine()
        .render_page(
            doc,
            1,
            RenderOptions {
                scale: 1.0,
                max_width_px: None,
            },
        )
        .await
        .unwrap();
    assert_eq!((full.width_px, full.height_px), (612, 792));
    assert_eq!(png_size(&full.png), (612, 792));

    let half = engine()
        .render_page(
            doc,
            1,
            RenderOptions {
                scale: 0.5,
                max_width_px: None,
            },
        )
        .await
        .unwrap();
    assert_eq!((half.width_px, half.height_px), (306, 396));

    let capped = engine()
        .render_page(
            doc,
            2,
            RenderOptions {
                scale: 2.0,
                max_width_px: Some(200),
            },
        )
        .await
        .unwrap();
    assert!(capped.width_px <= 200, "{}", capped.width_px);

    let bad = engine()
        .render_page(
            doc,
            1,
            RenderOptions {
                scale: 0.0,
                max_width_px: None,
            },
        )
        .await;
    assert!(matches!(bad, Err(DocumentError::Engine(_))));
    engine().close(doc).await.unwrap();
}

#[tokio::test]
async fn reports_errors() {
    assert_eq!(
        engine().open(&fixture("missing.pdf")).await,
        Err(DocumentError::NotFound)
    );
    assert!(matches!(
        engine().open(&fixture("corrupt.pdf")).await,
        Err(DocumentError::InvalidPdf(_))
    ));

    let doc = engine().open(&fixture("text.pdf")).await.unwrap();
    for page in [0, 3] {
        assert_eq!(
            engine().extract_text(doc, page).await,
            Err(DocumentError::PageOutOfRange {
                page,
                page_count: 2
            })
        );
    }
    engine().close(doc).await.unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn is_usable_from_many_tasks_at_once() {
    let engine: Arc<&'static PdfiumDocumentEngine> = Arc::new(engine());
    let tasks: Vec<_> = (0..16)
        .map(|i| {
            let engine = Arc::clone(&engine);
            tokio::spawn(async move {
                let name = if i % 2 == 0 { "text.pdf" } else { "mixed.pdf" };
                let doc = engine.open(&fixture(name)).await.unwrap();
                let text = engine.extract_text(doc, 1).await.unwrap();
                engine.close(doc).await.unwrap();
                text
            })
        })
        .collect();
    for task in tasks {
        assert!(!task.await.unwrap().trim().is_empty());
    }
}

#[tokio::test]
async fn password_protected_pdfs_are_reported_not_opened() {
    let err = engine().open(&fixture("encrypted.pdf")).await.unwrap_err();
    assert_eq!(err, DocumentError::PasswordRequired);
}

#[tokio::test]
async fn rotated_pages_keep_text_and_boxes_inside_the_page() {
    let doc = engine().open(&fixture("rotated.pdf")).await.unwrap();
    for page in 1..=2 {
        let info = engine().page_info(doc, page).await.unwrap();
        let spans = engine().text_spans(doc, page).await.unwrap();
        assert!(!spans.is_empty(), "page {page} has text");
        for s in &spans {
            let b = s.bbox;
            assert!(
                b.left >= -0.5
                    && b.top >= -0.5
                    && b.right <= info.width + 0.5
                    && b.bottom <= info.height + 0.5,
                "page {page}: {b:?} outside {}×{}",
                info.width,
                info.height
            );
        }
    }
    // Text on a rotated page is still found (and the page is not an OCR candidate).
    assert!(engine().page_info(doc, 2).await.unwrap().has_text);
    assert!(engine().pages_without_text(doc).await.unwrap().is_empty());
    let text = engine().extract_text(doc, 2).await.unwrap();
    assert!(text.contains("Página girada"), "{text:?}");
    engine().close(doc).await.unwrap();
}

#[tokio::test]
async fn extracts_accents_in_several_fonts() {
    let doc = engine().open(&fixture("unicode.pdf")).await.unwrap();
    let text = engine().extract_text(doc, 1).await.unwrap();
    for word in [
        "Ação",
        "coração",
        "pão",
        "avó",
        "órgão",
        "júri",
        "câmbio",
        "Über",
        "niño",
        "façade",
        "crème",
        "brûlée",
    ] {
        assert!(text.contains(word), "{word} in {text:?}");
    }
    let spans = engine().text_spans(doc, 1).await.unwrap();
    assert!(spans.iter().any(|s| s.bold) && spans.iter().any(|s| !s.bold));
    engine().close(doc).await.unwrap();
}

#[tokio::test]
async fn a_200_page_document_is_read_at_a_reasonable_pace() {
    let started = std::time::Instant::now();
    let doc = engine().open(&fixture("large.pdf")).await.unwrap();
    let count = engine().page_count(doc).await.unwrap();
    assert_eq!(count, 200);
    let mut chars = 0;
    for page in 1..=count {
        chars += engine()
            .text_spans(doc, page)
            .await
            .unwrap()
            .iter()
            .map(|s| s.text.len())
            .sum::<usize>();
    }
    engine().close(doc).await.unwrap();
    let secs = started.elapsed().as_secs_f64();
    eprintln!(
        "large.pdf: {count} pages in {secs:.2}s ({:.0} pages/s)",
        count as f64 / secs
    );
    assert!(chars > 200 * 300);
    // Generous bound (debug build, shared CI machines); `make bench` reports the real figure.
    assert!(secs < 30.0, "{secs}s");
}
